//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinimalPerfectHashConsole {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleOutput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleOutput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinimalPerfectHashConsole.ConsoleOutput", typeof(ConsoleOutput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal perfect hash took {0:N0} milliseconds to generate..
        /// </summary>
        internal static string DoneGeneratingMPH {
            get {
                return ResourceManager.GetString("DoneGeneratingMPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating {0:N0} keys..
        /// </summary>
        internal static string GeneratingKeys {
            get {
                return ResourceManager.GetString("GeneratingKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split {0:N0} keys into {1:N0} buckets, leaving {2:N0} buckets empty..
        /// </summary>
        internal static string MPHFilledBucketStats {
            get {
                return ResourceManager.GetString("MPHFilledBucketStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front loaded {0:N0} keys into the first {1:N0} buckets..
        /// </summary>
        internal static string MPHFrontLoadedStats {
            get {
                return ResourceManager.GetString("MPHFrontLoadedStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, couldn&apos;t verify minimal perfect hash..
        /// </summary>
        internal static string MPHInvalidHash {
            get {
                return ResourceManager.GetString("MPHInvalidHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified minimal perfect hash. All values from 0 to {0:N0} were found..
        /// </summary>
        internal static string VerifiedMPH {
            get {
                return ResourceManager.GetString("VerifiedMPH", resourceCulture);
            }
        }
    }
}
