//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foat.Hashing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logging {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logging() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foat.Hashing.Logging", typeof(Logging).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated number of front loaded keys is {0:N0}..
        /// </summary>
        internal static string MPHFrontLoadCutoff {
            get {
                return ResourceManager.GetString("MPHFrontLoadCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to generate a minimal perfect hash for {0:N0} keys..
        /// </summary>
        internal static string MPHGenStart {
            get {
                return ResourceManager.GetString("MPHGenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} of {1:N0}. Last bucket had {2:N0} keys. Last hash was {3:N0}..
        /// </summary>
        internal static string MPHHashBucketUpdate {
            get {
                return ResourceManager.GetString("MPHHashBucketUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashing buckets with multiple keys..
        /// </summary>
        internal static string MPHHashingBucketsWithMultipleKeys {
            get {
                return ResourceManager.GetString("MPHHashingBucketsWithMultipleKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashing buckets with 1 key..
        /// </summary>
        internal static string MPHHashingSingleBuckets {
            get {
                return ResourceManager.GetString("MPHHashingSingleBuckets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There will be {0:N0} buckets of which {1:N0} will be front loaded..
        /// </summary>
        internal static string MPHNumberOfBucketsWithFrontLoad {
            get {
                return ResourceManager.GetString("MPHNumberOfBucketsWithFrontLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to sort buckets by length..
        /// </summary>
        internal static string MPHStartingSort {
            get {
                return ResourceManager.GetString("MPHStartingSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to split the keys..
        /// </summary>
        internal static string MPHStartingSplit {
            get {
                return ResourceManager.GetString("MPHStartingSplit", resourceCulture);
            }
        }
    }
}
